# Site settings
title: PAMPANG
header-img: "img/facebook.jpg"
tagline: "cn"  
description: "庞伟湛"  
baseurl: ""
url: ""

# About/contact
owner: 
  name: " PAMPANG"
  email: fspwz@foxmail.com
  bio: "立志成为一名出色的前端工程师"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

github_username: pampang

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Gems
gems: [jekyll-paginate]
paginate: 8
paginate_path: "page:num"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Guangzhou

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "pampang"
      header-img: "img/facebook.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : pampang
  disqus :
      short_name : pampang

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation